# Generated by Django 5.2.5 on 2025-09-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("carrera", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=20)),
                ("rol", models.CharField(max_length=50)),
                ("contrasena", models.CharField(max_length=128)),
            ],
        ),
    ]