# Generated by Django 5.2.5 on 2025-09-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_carrera_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
