# Generated by Django 5.2.5 on 2025-10-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemaDisponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("carrera", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("requisitos", models.JSONField(blank=True, default=list)),
                ("cupos", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temas_disponibles",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "temas_disponibles",
                "ordering": ["-created_at"],
            },
        ),
    ]