# Generated by Django 5.2.5 on 2025-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Computación', 'Computación'), ('Informática', 'Informática'), ('Industria', 'Industria'), ('Trabajo Social', 'Trabajo Social'), ('Mecánica', 'Mecánica'), ('Ing. Civil en Computación mención Informática', 'Ing. Civil en Computación mención Informática')], max_length=50, null=True),
        ),
    ]
