# Generated by Django 5.2.5 on 2025-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_practicadocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('general', 'General'), ('tema', 'Tema'), ('inscripcion', 'Inscripción')], default='general', max_length=40),
        ),
    ]
