# Generated by Django 5.2.5 on 2025-10-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_practicadocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudcartapractica",
            name="documento",
            field=models.FileField(
                blank=True, null=True, upload_to="practicas/cartas/%Y/%m/%d"
            ),
        ),
    ]