# Generated by Django 5.2.5 on 2025-10-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_solicitudcartapractica_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('general', 'General'), ('tema', 'Tema'), ('inscripcion', 'Inscripción')], default='general', max_length=40),
        ),
    ]
