# Generated by Django 5.2.5 on 2025-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_notificacion_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripciontema",
            name="es_responsable",
            field=models.BooleanField(default=False),
        ),
    ]