# Generated by Django 5.2.5 on 2025-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_notificacion_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripciontema",
            name="es_responsable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propuestatema",
            name="correos_companeros",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="propuestatema",
            name="cupos_requeridos",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="propuestatema",
            name="cupos_maximo_autorizado",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propuestatema",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pendiente_ajuste", "Pendiente ajuste"),
                    ("pendiente_aprobacion", "Pendiente aprobación"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
