# Generated by Django 5.2.5 on 2025-11-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaTemaDocente',
            fields=[
            ],
            options={
                'verbose_name': 'Propuesta tema docente',
                'verbose_name_plural': 'Propuestas tema docente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.propuestatema',),
        ),
        migrations.AlterModelOptions(
            name='propuestatema',
            options={'ordering': ['-created_at'], 'verbose_name': 'Propuesta tema alumno', 'verbose_name_plural': 'Propuestas temas alumno'},
        ),
        migrations.AddField(
            model_name='inscripciontema',
            name='es_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propuestatema',
            name='correos_companeros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propuestatema',
            name='cupos_maximo_autorizado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propuestatema',
            name='cupos_requeridos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='temadisponible',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_a_cargo', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='temadisponible',
            name='propuesta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tema_generado', to='api.propuestatema'),
        ),
        migrations.AddField(
            model_name='temadisponible',
            name='rama',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='propuestatema',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_ajuste', 'Pendiente ajuste'), ('pendiente_aprobacion', 'Pendiente aprobación'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
