# Generated by Django 5.2.5 on 2025-11-17 02:41

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_propuestatemadocente_alter_propuestatema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='docente_guia',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_guia', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('propuesta', 'Propuesta'), ('general', 'General'), ('tema', 'Tema'), ('reunion', 'Reunión'), ('inscripcion', 'Inscripción')], default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EvaluacionGrupoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=160)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Evaluada', 'Evaluada')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_grupo', to='api.usuario')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_docente', to='api.temadisponible')),
            ],
            options={
                'db_table': 'evaluaciones_grupo_docente',
                'ordering': ['grupo_nombre', '-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEntregaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=api.models.evaluacion_entrega_upload_to)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_revision', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, limit_choices_to={'rol': 'alumno'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_evaluaciones', to='api.usuario')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.evaluaciongrupodocente')),
            ],
            options={
                'db_table': 'evaluaciones_entregas_alumno',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('disponibilidad_sugerida', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reunion', to='api.usuario')),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reunion_recibidas', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Solicitud reuniones alumno',
                'verbose_name_plural': 'Solicitudes reuniones alumno',
                'db_table': 'solicitudes_reunion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], max_length=20)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('finalizada', 'Finalizada'), ('no_realizada', 'No realizada'), ('reprogramada', 'Reprogramada')], default='aprobada', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_alumno', to='api.usuario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_registradas', to='api.usuario')),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_docente', to='api.usuario')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion', to='api.solicitudreunion')),
            ],
            options={
                'verbose_name': 'Solicitud reuniones docente',
                'verbose_name_plural': 'Solicitudes reuniones docente',
                'db_table': 'reuniones',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion_solicitud', 'Creación de solicitud'), ('aprobada_desde_solicitud', 'Aprobada desde solicitud'), ('agendada_directamente', 'Agendada directamente'), ('rechazo', 'Rechazo'), ('cierre_final', 'Cierre final')], max_length=40)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazabilidad', to='api.reunion')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trazabilidad', to='api.solicitudreunion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'trazabilidad_reuniones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluaciongrupodocente',
            index=models.Index(fields=['docente', 'grupo_nombre', 'estado'], name='evaluacione_docente_ad2197_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluaciongrupodocente',
            index=models.Index(fields=['tema', 'fecha'], name='evaluacione_tema_id_d8f970_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionentregaalumno',
            index=models.Index(fields=['evaluacion', 'alumno', 'estado_revision'], name='evaluacione_evaluac_3ae986_idx'),
        ),
        migrations.AddIndex(
            model_name='reunion',
            index=models.Index(fields=['docente', 'fecha', 'hora_inicio', 'hora_termino'], name='reuniones_docente_4c5192_idx'),
        ),
    ]
