# Generated by Django 5.2.5 on 2025-11-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_inscripciontema_es_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="propuestatema",
            name="correos_companeros",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="propuestatema",
            name="cupos_requeridos",
            field=models.PositiveIntegerField(default=1),
        ),
    ]