# Generated by Django 5.2.5 on 2025-11-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_inscripciontema_es_responsable"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]