# Generated by Django 5.2.5 on 2025-11-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_propuestatema_correos_companeros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propuestatema",
            name="cupos_maximo_autorizado",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propuestatema",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pendiente_ajuste", "Pendiente ajuste"),
                    ("pendiente_aprobacion", "Pendiente aprobación"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
