# Generated by Django 5.2.5 on 2025-11-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_propuestatema_correos_companeros_and_more"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]