# Generated by Django 5.2.5 on 2025-11-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_propuestatema_ensure_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="temadisponible",
            name="docente_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temas_a_cargo",
                to="api.usuario",
            ),
        ),
    ]
