# Generated by Django 5.2.5 on 2025-11-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_temadisponible_docente_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropuestaTemaDocente",
            fields=[],
            options={
                "verbose_name": "Propuesta tema docente",
                "verbose_name_plural": "Propuestas tema docente",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("api.propuestatema",),
        ),
        migrations.AlterModelOptions(
            name="propuestatema",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Propuesta tema alumno",
                "verbose_name_plural": "Propuestas temas alumno",
            },
        ),
        migrations.AddField(
            model_name="temadisponible",
            name="propuesta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tema_generado",
                to="api.propuestatema",
            ),
        ),
    ]