# Generated by Django 5.2.5 on 2025-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_propuestatemadocente_alter_propuestatema_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temadisponible",
            name="rama",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]