# Generated by Django 5.2.5 on 2025-11-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_temadisponible_rama"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="docente_guia",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "docente"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alumnos_guia",
                to="api.usuario",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudReunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                (
                    "disponibilidad_sugerida",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_reunion",
                        to="api.usuario",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "docente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_reunion_recibidas",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "solicitudes_reunion",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Reunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_termino", models.TimeField()),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("online", "Online")],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField()),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("aprobada", "Aprobada"),
                            ("finalizada", "Finalizada"),
                            ("no_realizada", "No realizada"),
                            ("reprogramada", "Reprogramada"),
                        ],
                        default="aprobada",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_alumno",
                        to="api.usuario",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_registradas",
                        to="api.usuario",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "docente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuniones_docente",
                        to="api.usuario",
                    ),
                ),
                (
                    "solicitud",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunion",
                        to="api.solicitudreunion",
                    ),
                ),
            ],
            options={
                "db_table": "reuniones",
                "ordering": ["-fecha", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TrazabilidadReunion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("creacion_solicitud", "Creación de solicitud"),
                            ("aprobada_desde_solicitud", "Aprobada desde solicitud"),
                            ("agendada_directamente", "Agendada directamente"),
                            ("rechazo", "Rechazo"),
                            ("cierre_final", "Cierre final"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado_nuevo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                ("datos", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "reunion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trazabilidad",
                        to="api.reunion",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trazabilidad",
                        to="api.solicitudreunion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "trazabilidad_reuniones",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="reunion",
            index=models.Index(
                fields=["docente", "fecha", "hora_inicio", "hora_termino"],
                name="reuniones_docente_4c5192_idx",
            ),
        ),
    ]
