# Generated by Django 5.2.5 on 2025-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_usuario_docente_guia_solicitudreunion_reunion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("propuesta", "Propuesta"),
                    ("general", "General"),
                    ("tema", "Tema"),
                    ("reunion", "Reunión"),
                    ("inscripcion", "Inscripción"),
                ],
                default="general",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]