# Generated by Django 5.2.5 on 2025-11-14 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_notificacion_tipo_alter_usuario_rut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reunion",
            options={
                "ordering": ["-fecha", "-hora_inicio"],
                "verbose_name": "Solicitud reuniones docente",
                "verbose_name_plural": "Solicitudes reuniones docente",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudreunion",
            options={
                "ordering": ["-creado_en"],
                "verbose_name": "Solicitud reuniones alumno",
                "verbose_name_plural": "Solicitudes reuniones alumno",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionGrupoDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo_nombre", models.CharField(max_length=160)),
                ("titulo", models.CharField(max_length=200)),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En progreso", "En progreso"),
                            ("Evaluada", "Evaluada"),
                        ],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "docente"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_grupo",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "evaluaciones_grupo_docente",
                "ordering": ["grupo_nombre", "-fecha", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["docente", "grupo_nombre", "estado"],
                        name="evaluacione_docente_ad2197_idx",
                    )
                ],
            },
        ),
    ]