# Generated by Django 5.2.5 on 2025-11-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_reunion_options_alter_solicitudreunion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="tema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluaciones_docente",
                to="api.temadisponible",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluaciongrupodocente",
            index=models.Index(
                fields=["tema", "fecha"], name="evaluacione_tema_id_d8f970_idx"
            ),
        ),
    ]
