# Generated by Django 5.2.5 on 2025-11-18 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_evaluacionentregaalumno"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticaFirmaCoordinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera",
                    models.CharField(
                        choices=[
                            ("Química y Farmacia", "Química y Farmacia"),
                            ("Ing. Civil Biomédica", "Ing. Civil Biomédica"),
                            ("Ing. Civil Química", "Ing. Civil Química"),
                            ("Ing. Civil Matemática", "Ing. Civil Matemática"),
                            (
                                "Bachillerato en Ciencias de la Ing.",
                                "Bachillerato en Ciencias de la Ing.",
                            ),
                            ("Dibujante Proyectista", "Dibujante Proyectista"),
                            (
                                "Ing. Civil en Ciencia de Datos",
                                "Ing. Civil en Ciencia de Datos",
                            ),
                            (
                                "Ing. Civil en Computación mención Informática",
                                "Ing. Civil en Computación mención Informática",
                            ),
                            ("Ing. Civil Electrónica", "Ing. Civil Electrónica"),
                            ("Ing. Civil en Mecánica", "Ing. Civil en Mecánica"),
                            ("Ing. Civil Industrial", "Ing. Civil Industrial"),
                            ("Ing. en Biotecnología", "Ing. en Biotecnología"),
                            ("Ing. en Geomensura", "Ing. en Geomensura"),
                            ("Ing. en Alimentos", "Ing. en Alimentos"),
                            ("Ing. en Informática", "Ing. en Informática"),
                            ("Ing. Industrial", "Ing. Industrial"),
                            ("Química Industrial", "Química Industrial"),
                            ("Ing. Electrónica", "Ing. Electrónica"),
                        ],
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("archivo", models.FileField(upload_to="practicas/firmas/%Y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firmas_practica",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "practica_firmas_coordinador",
                "ordering": ["-updated_at"],
            },
        ),
    ]