# Generated by Django 5.2.5 on 2025-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_practicafirmacoordinador"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudcartapractica",
            name="practica_correo_encargado",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
    ]