# Generated by Django 5.2.5 on 2025-11-19 03:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_practicafirmacoordinador"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="pauta",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.evaluacion_pauta_upload_to
            ),
        ),
    ]
