# Generated by Django 5.2.5 on 2025-11-20 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_evaluaciongrupodocente_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="fecha_extendida",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evaluaciongrupodocente",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "PENDIENTE"),
                    ("FUERA DE PLAZO", "FUERA DE PLAZO"),
                    ("COMPLETADO DENTRO DE PLAZO", "COMPLETADO DENTRO DE PLAZO"),
                    ("ENTREGADO FUERA DE PLAZO", "ENTREGADO FUERA DE PLAZO"),
                ],
                default="PENDIENTE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongrupodocente",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
