# Generated by Django 5.2.5 on 2025-11-25 01:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_evaluacionentregaalumno_archivos_docente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluacionentregaalumno",
            name="archivo",
            field=models.FileField(
                max_length=255, upload_to=api.models.evaluacion_entrega_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionentregaalumno",
            name="informe_corregido",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=api.models.evaluacion_entrega_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="evaluacionentregaalumno",
            name="rubrica_docente",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=api.models.evaluacion_entrega_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="evaluaciongrupodocente",
            name="rubrica",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=api.models.evaluacion_rubrica_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="practicadocumento",
            name="archivo",
            field=models.FileField(
                max_length=255, upload_to="practicas/documentos/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="practicafirmacoordinador",
            name="archivo",
            field=models.FileField(
                max_length=255, upload_to="practicas/firmas/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudcartapractica",
            name="documento",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="practicas/cartas/%Y/%m/%d",
            ),
        ),
    ]