# Generated by Django 5.2.5 on 2025-11-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_evaluacionentregaalumno_archivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="bitacora_comentario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluaciongrupodocente",
            name="bitacoras_requeridas",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]