# Generated by Django 5.2.5 on 2025-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_evaluaciongrupodocente_bitacora_comentario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacionentregaalumno",
            name="bitacora_indice",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluacionentregaalumno",
            name="es_bitacora",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="evaluacionentregaalumno",
            index=models.Index(
                fields=["evaluacion", "alumno", "es_bitacora", "bitacora_indice"],
                name="evaluacione_bitacor_idx",
            ),
        ),
    ]
