# Generated by Django 5.2.5 on 2025-11-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_evaluacionentregaalumno_bitacora_indice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicafirmacoordinador",
            options={},
        ),
        migrations.CreateModel(
            name="PracticaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrera", models.CharField(max_length=160)),
                ("nombre", models.CharField(max_length=160)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "archivo",
                    models.FileField(
                        max_length=255, upload_to="practicas/evaluaciones/%Y/%m/%d"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_practica",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "practica_evaluaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticaEvaluacionEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=255,
                        upload_to="practicas/evaluaciones/entregas/%Y/%m/%d",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_practica",
                        to="api.usuario",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="api.practicaevaluacion",
                    ),
                ),
            ],
            options={
                "db_table": "practica_evaluacion_entregas",
                "ordering": ["-created_at"],
            },
        ),
    ]