# Generated by Django 5.2.5 on 2025-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_alter_practicafirmacoordinador_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicaevaluacionentrega",
            name="nota",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]