# Generated by Django 5.2.5 on 2025-11-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_practicaevaluacionentrega_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicaevaluacionentrega",
            name="evaluacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas",
                to="api.practicaevaluacion",
            ),
        ),
    ]