# Generated by Django 5.2.5 on 2025-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_practicaevaluacionentrega_evaluacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicafirmacoordinador",
            name="url_firma_digital",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="practicafirmacoordinador",
            name="archivo",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="practicas/firmas/%Y/%m/%d",
            ),
        ),
    ]