# Generated by Django 5.2.5 on 2025-11-15 01:58

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_evaluaciongrupodocente_tema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluacionEntregaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(upload_to=api.models.evaluacion_entrega_upload_to),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "estado_revision",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("revisada", "Revisada")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "alumno"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas_evaluaciones",
                        to="api.usuario",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="api.evaluaciongrupodocente",
                    ),
                ),
            ],
            options={
                "db_table": "evaluaciones_entregas_alumno",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["evaluacion", "alumno", "estado_revision"],
                        name="evaluacione_evaluac_3ae986_idx",
                    )
                ],
            },
        ),
    ]