from django.urls import path, re_path

from .views import (
    login_view,
    TemaDisponibleListCreateView,
    reservar_tema,
    asignar_companeros,
    tema_disponible_detalle,
    crear_solicitud_carta_practica,
    listar_solicitudes_carta_practica,
    aprobar_solicitud_carta_practica,
    rechazar_solicitud_carta_practica,
    gestionar_solicitudes_reunion,
    aprobar_solicitud_reunion,
    rechazar_solicitud_reunion,
    gestionar_reuniones,
    cerrar_reunion,
    PropuestaTemaListCreateView,
    PropuestaTemaRetrieveUpdateView,
    DocenteListView,
    NotificacionListView,
    marcar_notificacion_leida,
    gestionar_documentos_practica,
    eliminar_documento_practica,
    gestionar_firma_coordinador_practica,
    DocenteEvaluacionListCreateView,
    DocenteEvaluacionEntregaUpdateView,
    DocenteGruposActivosListView,
    CoordinacionPromediosTituloView,
    AlumnoEvaluacionListView,
    AlumnoEvaluacionEntregaListCreateView,
)

urlpatterns = [
    path("login", login_view, name="login"),
    path("temas/", TemaDisponibleListCreateView.as_view(), name="temas-disponibles"),
    path(
        "temas/<int:pk>/",
        tema_disponible_detalle,
        name="tema-detalle",
    ),
    path(
        "temas/<int:pk>/reservas/",
        reservar_tema,
        name="tema-reservar",
    ),
    path(
        "temas/<int:pk>/companeros/",
        asignar_companeros,
        name="tema-companeros",
    ),
    path("docentes/", DocenteListView.as_view(), name="lista-docentes"),
    path("propuestas/", PropuestaTemaListCreateView.as_view(), name="propuestas"),
    path(
        "propuestas/<int:pk>/",
        PropuestaTemaRetrieveUpdateView.as_view(),
        name="detalle-propuesta",
    ),
    path(
        "notificaciones/",
        NotificacionListView.as_view(),
        name="lista-notificaciones",
    ),
    path(
        "notificaciones/<int:pk>/leer/",
        marcar_notificacion_leida,
        name="marcar-notificacion-leida",
    ),
    re_path(
        r"^practicas/solicitudes-carta/?$",
        crear_solicitud_carta_practica,
        name="crear-solicitud-carta-practica",
    ),
    re_path(
        r"^practicas/solicitudes-carta/listar/?$",
        listar_solicitudes_carta_practica,
        name="listar-solicitudes-carta-practica-alumno",
    ),
    re_path(
        r"^coordinacion/solicitudes-carta/?$",
        listar_solicitudes_carta_practica,
        name="listar-solicitudes-carta-practica",
    ),
    re_path(
        r"^coordinacion/solicitudes-carta/(?P<pk>\d+)/aprobar/?$",
        aprobar_solicitud_carta_practica,
        name="aprobar-solicitud-carta-practica",
    ),
    re_path(
        r"^coordinacion/solicitudes-carta/(?P<pk>\d+)/rechazar/?$",
        rechazar_solicitud_carta_practica,
        name="rechazar-solicitud-carta-practica",
    ),
    path(
        "coordinacion/practicas/documentos/",
        gestionar_documentos_practica,
        name="gestionar-documentos-practica",
    ),
    path(
    "coordinacion/practicas/firma/",
    gestionar_firma_coordinador_practica,
    name="gestionar-firma-coordinador-practica",
    ),
    path(
        "coordinacion/practicas/documentos/<int:pk>/",
        eliminar_documento_practica,
        name="eliminar-documento-practica",
    ),
    path(
    "coordinacion/titulo/promedios/",
    CoordinacionPromediosTituloView.as_view(),
    name="coordinacion-promedios-titulo",
    ),
    path(
        "practicas/documentos/",
        gestionar_documentos_practica,
        name="listar-documentos-practica",
    ),
    path(
        "reuniones/solicitudes/",
        gestionar_solicitudes_reunion,
        name="gestionar-solicitudes-reunion",
    ),
    path(
        "reuniones/solicitudes/<int:pk>/aprobar/",
        aprobar_solicitud_reunion,
        name="aprobar-solicitud-reunion",
    ),
    path(
        "reuniones/solicitudes/<int:pk>/rechazar/",
        rechazar_solicitud_reunion,
        name="rechazar-solicitud-reunion",
    ),
    path(
        "reuniones/",
        gestionar_reuniones,
        name="gestionar-reuniones",
    ),
    path(
        "reuniones/<int:pk>/cerrar/",
        cerrar_reunion,
        name="cerrar-reunion",
    ),
    path(
        "docentes/evaluaciones/",
        DocenteEvaluacionListCreateView.as_view(),
        name="docente-evaluaciones",
    ),
    path(
        "docentes/grupos/activos/",
        DocenteGruposActivosListView.as_view(),
        name="docente-grupos-activos",
    ),
    path(
        "alumnos/evaluaciones/",
        AlumnoEvaluacionListView.as_view(),
        name="alumno-evaluaciones",
    ),
    path(
        "alumnos/evaluaciones/<int:pk>/entregas/",
        AlumnoEvaluacionEntregaListCreateView.as_view(),
        name="alumno-evaluacion-entregas",
    ),
    path(
        "docentes/evaluaciones/entregas/<int:pk>/",
        DocenteEvaluacionEntregaUpdateView.as_view(),
        name="docente-evaluacion-actualizar-entrega",
    ),
]